### ISSUE TITLE
sample code blocks should specify language as sh

### ISSUE THREAD

**Issue by anntzer** [matthew-brett/gitwash#10]
Currently, code blocks in doc produced by gitwash do not specify a language (e.g. https://raw.githubusercontent.com/matthew-brett/gitwash/master/gitwash/patching.rst, note the bare `::`).  As a consequence, they are highlighted as python code if the project defaults to such a language, e.g. http://matplotlib.org/devel/gitwash/patching.html#overview.

It should be sufficient to add a `highlight` directive (http://www.sphinx-doc.org/en/stable/markup/code.html#directive-highlight) at the top of every gitwash file (I think).

**Comment by matthew-brett** [comment]
Thanks - I've added `highlight` directives and a few ``code-block:: none`` directives - see e488a11.   A built result is over at (e.g) :  https://matthew-brett.github.io/pydagogue/gitwash/patching.html
